### ISSUE TITLE
Enum creator for other font files

### ISSUE THREAD

**Issue by npagare** [smourier/FontAwesomeEnum#3]
Hi @smourier , thank you very much for your help.

Do you have a similar version for creating enum for any other font (ttf) files beside FontAwesome?
It will be very very helpful to have it.

Also, any recommendations on creating a new font file using a set of icon images?

Thanks.

**Comment by smourier** [comment]
Hi,

It cannot work for *any* font because glyphs have no names. FontAwesomeEnum extracts names from the CSS that's provided in FA's package.

However it can be adapted for any package (font + css) that's *similar* to FA, that's what I did for Material Design font: https://github.com/smourier/MaterialDesignIconsEnum.

And, no I don't have any recommendation for creating font file.
